---
title: "I. Calculate Noncompliance Rates"
output: html_document
---

# Open data
```{r}
#install packages
install.packages("reshape2")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("lubridate")
install.packages("tcltk")
install.packages("rJava")

#load packages
library(reshape2)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tcltk)
library(rJava)

#open sample dataset
assessment_example <- read.csv("Manual assessment sample dataset.csv",header = T, stringsAsFactors = F)

```

# a.	For the latest assessment in a given data frame
```{r}

get_compliance_question_for_all_by_country <- function(df){
    temp_df <- df
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Cycle <- as.numeric(temp_df$Cycle)
    
    latest_date_for_each_factory <- temp_df %>%
      group_by(Factory.Assessed.Name)%>%
      summarise(Quest.ID = max(Quest.ID))
  
    temp_df <- inner_join(temp_df,latest_date_for_each_factory,
                           by = c('Factory.Assessed.Name','Quest.ID'))

    summary(temp_df$latest_assessment_date) 

    temp_df <- temp_df[temp_df$Question.type != "FGW",]

    temp_df$Finding <- as.integer(temp_df$Finding)

    temp_df$public_reporting <- ifelse(grepl("Public Disclosure",temp_df$Tags),1,0)
    
    compliance_question_count <- temp_df%>%
      group_by(Country,Q.Label,CP,Cluster,public_reporting,Tags)%>%
      summarise(number_nc_factories_in_cycle = sum(Finding), total_factories_in_cycle = n_distinct(Quest.ID), 
                percent_nc = sum(Finding)/n_distinct(Quest.ID))
      
    return (compliance_question_count)
}

#use the function
noncompliance_example_latest<- get_compliance_question_for_all_by_country(assessment_example)

```

# b.	For a chosen cycle in a given data frame
```{r}
#store the function
get_compliance_for_a_chosen_cycle <- function(df,cycle){
    temp_df <- df
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
    temp_df <- temp_df[!duplicated(temp_df),]
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Cycle <- as.numeric(temp_df$Cycle)
    temp_df <- temp_df[temp_df$Cycle == cycle,]
    temp_df <- temp_df[temp_df$Question.type != "FGW",]
    temp_df$Finding <- as.integer(temp_df$Finding)
    
    # Making some modifications to consolidate the hazardous forms
    haz_and_worst_forms <- c("Hazardous Work","Hazardous Work and other Worst Forms","Unconditional Worst Forms")
    temp_df$CP<- ifelse(temp_df$CP %in% haz_and_worst_forms,"Hazardous Work and other Worst forms",temp_df$CP) 

    compliance_calc <- temp_df%>%
      group_by(Country,Cluster, Quest.ID,CP,Cycle)%>%
      summarise(findings = sum(Finding))
    
    compliance_calc$non_compliant <-ifelse(compliance_calc$findings >0,1,0)

    compliance_df <- compliance_calc%>%
      group_by(Country,CP,Cluster,Cycle)%>%
      summarise(total_factories=n(),number_non_compliant= sum(non_compliant), percent_non_cp = sum(non_compliant)/n())
    return (compliance_df)
}

#use the function
noncompliance_example_firstcycle<- get_compliance_for_a_chosen_cycle(assessment_example,1)

# count the factories
number_factories_in_cycle_one <- noncompliance_example_firstcycle%>%
  group_by(Country,Cycle)%>%
  summarise(factories = max(total_factories))
  
#save the output as a .csv
write.csv(noncompliance_example_cycles, "Noncompliance CP level by cycle.csv")
```

# c.	For a Multi-Country Balanced Panel Dataset
```{r}
#open data for multiple countries
jordan_assessment <- read.csv("Jordan assessment through Aug 23 2018.csv",header = T, stringsAsFactors = F)

indonesia_assessment <- read.csv("Indonesia All through Aug 23 2018.csv", header = T, stringsAsFactors = F)

bangladesh_assessment <- read.csv("Bangladesh assessment through Aug 23 2018.csv" ,header =T, stringsAsFactors = F)

#create a multi-country dataset
multicountry_dataset <- rbind(jordan_assessment,indonesia_assessment,bangladesh_assessment)

table_of_cycle_countries <- multicountry_dataset%>%
  group_by(Country,Cycle)%>%
  summarise(number_of_factories = n_distinct(Factory.Assessed.ID))

#visually inspect the sample size 
table_to_inspect_sample_size <- dcast(table_of_cycle_countries,Country ~ Cycle, value.var="number_of_factories")
View(table_to_inspect_sample_size)

#store the function
get_nc_rates_by_cycle_for_all_cycles_less_than_a_given_cycle <- function(df,cyc){
  temp_df <- df
  temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
  temp_df <- temp_df[!duplicated(temp_df),]
  temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
  temp_df$Cycle <- as.numeric(temp_df$Cycle)

  factory_ids_we_want <- df%>%
    group_by(Factory.Assessed.ID)%>%
    summarise(largest_cycle = max(Cycle))%>%
    filter(largest_cycle >= cyc)
  
  temp_df <- temp_df%>%
    filter(Factory.Assessed.ID %in% factory_ids_we_want$Factory.Assessed.ID 
           & Cycle <= cyc & Question.type != "FGW")

  temp_df$Finding <- as.integer(temp_df$Finding)


    # Making some modifications to consolidate the hazardous forms and the OSH cluster
    
  haz_and_worst_forms <- c("Hazardous Work","Hazardous Work and other Worst Forms","Unconditional Worst Forms")

  temp_df$CP<- ifelse(temp_df$CP %in% haz_and_worst_forms,"Hazardous Work and other Worst forms",temp_df$CP)
  temp_df$Cluster <- ifelse(temp_df$Cluster == "Systems", "Occupational Safety and Health", temp_df$Cluster)  

  compliance_calc <- temp_df%>%
    group_by(Country,Cluster, Quest.ID,CP,Cycle)%>%
    summarise(findings = sum(Finding))
    
  compliance_calc$non_compliant <-ifelse(compliance_calc$findings >0,1,0)

  compliance_df <- compliance_calc%>%
    group_by(Country,CP,Cluster,Cycle)%>%
    summarise(total_factories=n(),number_non_compliant= sum(non_compliant), percent_non_cp = sum(non_compliant)/n())

    return (compliance_df)  
}


#use the function (example) 
nc_cp_trends <- get_nc_rates_by_cycle_for_all_cycles_less_than_a_given_cycle(multicountry_dataset,3)

#Save the table as a .csv
write.csv(nc_cp_trends, "Noncompliance CP trends panel data countries.csv")

```
