---
title: "2.1.3 Summarize data (CP level)"
output: html_document
---

# Run before summarizing data
```{r}
#install packages
install.packages("reshape2")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("lubridate")
install.packages("tcltk")
install.packages("rJava")

#load packages
library(reshape2)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tcltk)
library(rJava)

#open sample dataset
assessment_example <- read.csv("Manual assessment sample dataset.csv",header = T, stringsAsFactors = F)

```

# Number of factories per cycle
```{r}
cycle_and_presence <- assessment_example%>%
  group_by(Cycle)%>%
  summarise(n_factories = n_distinct(Quest.ID))

```

# Noncompliance at the CP level: by latest assessment in specified dates
```{r}
#store the function
get_compliance_data_passing_df <- function(df,m1,m2,y1,y2){
     temp_df <- df
    #get rid of any observation deemed (Obsolete)
    # temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Year <- as.numeric(format(temp_df$date_final, "%Y"))
    temp_df$Month <- as.numeric(format(temp_df$date_final, "%m"))
    if(y1 == y2){
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1 & temp_df$Month <= m2),]
    }else{
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1) | # keep if year = y1 first year and greater first month we keep it
                                 (temp_df$Year == y2 & temp_df$Month <= m2)| #keep it if it's in the last year but smaller than the final month
                         (temp_df$Year > y1 & temp_df$Year < y2),]
    } # keep intermediate years!
    latest_date_for_each_factory <- temp_df %>%
      group_by(Factory.Assessed.ID)%>%
      summarise(Quest.ID = max(Quest.ID))
    temp_df <- inner_join(temp_df,latest_date_for_each_factory,
                           by = c('Factory.Assessed.ID','Quest.ID'))
    temp_df <- temp_df[temp_df$Question.type != "FGW",]
    temp_df$Finding <- as.integer(temp_df$Finding)
    compliance_calc <- temp_df%>%
      group_by(Factory.Assessed.ID, Cluster, Quest.ID,CP)%>%
      summarise(findings = sum(Finding))
    compliance_calc$non_compliant <-ifelse(compliance_calc$findings >0,1,0)
     compliance_df <- compliance_calc%>%
      group_by(CP,Cluster)%>%
      summarise(total_factories=n(),number_non_compliant= sum(non_compliant), percent_non_cp = sum(non_compliant)/n())
    return (compliance_df)
}

#use the function (example)
#here, we calculate noncompliance rates between June 2015 and July 2017, but they can be replaced with different timeframe following the order "m1, m2, y1, y2," where m1 and y1 is the start date (month and year), and m2 and y2 the end date of the timeframe taken into consideration
noncompliance_rate_example <-get_compliance_data_passing_df(assessment_example,6,7,2015,2017)
```

# Noncompliance at the CP level: For a chosen cycle in specified dates
```{r}
#store the function
get_compliance_data_date_and_cycle <- function(df,m1,m2,y1,y2,cycle){
    temp_df <- df
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Year <- as.numeric(format(temp_df$date_final, "%Y"))
    temp_df$Month <- as.numeric(format(temp_df$date_final, "%m"))
   
    if(y1 == y2){
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1 & temp_df$Month <= m2),]
    }else{
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1) |
                                 (temp_df$Year == y2 & temp_df$Month <= m2)|
                         (temp_df$Year > y1 & temp_df$Year < y2),]
    }
    temp_df <- temp_df[temp_df$Cycle == cycle,]
   
    
    temp_df <- temp_df[temp_df$Question.type != "FGW",]
 
    temp_df$Finding <- as.integer(temp_df$Finding)
 
    compliance_calc <- temp_df%>%
      group_by(Factory.Assessed.ID, Cluster, Quest.ID,CP)%>%
      summarise(findings = sum(Finding))
   
    compliance_calc$non_compliant <-ifelse(compliance_calc$findings >0,1,0)
 
    compliance_df <- compliance_calc%>%
      group_by(CP,Cluster)%>%
      summarise(total_factories=n(),number_non_compliant= sum(non_compliant), percent_non_cp = sum(non_compliant)/n())
 
    return (compliance_df)
}

#use the function (example)
#here, we calculate noncompliance rates between June 2015 and July 2017 for all first assessment cycles. The criteria can be replaced with a different timeframe and cycle number following the order: "m1, m2, y1, y2, cycle" where m1 and y1 is the start date (month and year), and m2 and y2 the end date of the specified timeframe, and cycle is the cycle number that we wish to take into consideration. 
noncompliance_cp_example_cycle <- get_compliance_data_date_and_cycle(assessment_example,6,7,2015,2017,1)
```

# Noncompliance at the CP level: By latest date in a given time frame for each factory
```{r}
#store the function
get_compliance_each_factory_dates_cp <- function(df,m1,m2,y1,y2){
    temp_df <- df
    #get rid of any observation deemed (Obsolete)
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
    temp_df <- temp_df[!duplicated(temp_df),]
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Year <- as.numeric(format(temp_df$date_final, "%Y"))
    temp_df$Month <- as.numeric(format(temp_df$date_final, "%m"))
   
    if(y1 == y2){
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1 & temp_df$Month <= m2),]
    }else{
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1) |
                                 (temp_df$Year == y2 & temp_df$Month <= m2)|
                         (temp_df$Year > y1 & temp_df$Year < y2),]
    }
   
    latest_date_for_each_factory <- temp_df %>%
      group_by(Factory.Assessed.ID)%>%
      summarise(Quest.ID = max(Quest.ID))

    temp_df <- inner_join(temp_df,latest_date_for_each_factory,
                           by = c('Factory.Assessed.ID','Quest.ID'))
 
    temp_df <- temp_df[temp_df$Question.type != "FGW",]
 
    temp_df$Finding <- as.integer(temp_df$Finding)
 
    compliance_calc <- temp_df%>%
      group_by(Factory.Assessed.ID, Cluster, Quest.ID,CP)%>%
      summarise(findings = sum(Finding))
   
    compliance_calc$non_compliant <-ifelse(compliance_calc$findings >0,1,0)
 
    compliance_df <- compliance_calc%>%
      group_by(Factory.Assessed.ID,CP,Cluster)%>%
      summarise(total_factories=n(),number_non_compliant= sum(non_compliant), percent_non_cp = sum(non_compliant)/n())
 
    factory_level_average_nc <- compliance_df%>%
      group_by(Factory.Assessed.ID)%>%
      summarise(total_cp_nc = sum(number_non_compliant), total_cps = n(), factory_cp_level_nc_rate = sum(number_non_compliant)/n())
   
    return (factory_level_average_nc)
}

#use the function (example)
#here, we calculate noncompliance rates between January and December 2012. The specified dates can be replaced with a different timeframe following the order: "m1, m2, y1, y2," where m1 and y1 is the start date (month and year), and m2 and y2 the end date of the specified timeframe
noncompliance_example_factory <- get_compliance_each_factory_dates_cp(assessment_example,1,12,2012,2012)
```
